remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Project 3
description: In this project we had further practice writing and executing non-web server Node.js JavaScript code using VSCode. We also focused on fastify and GET verb, as well as  loading a file and using as a web page
